services:
  sigmaBoyPostgres:
    image: postgres
    container_name: apiGateway
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apiGateway
    restart: unless-stopped
    ports:
      - "9998:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
