services:
  sigmaBoyPostgres:
    image: postgres
    container_name: sigmaBoy
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sigmaBoy
    restart: unless-stopped
    ports:
      - "9999:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: